# WGID Folder structure
"{job}":
  # Show software configs
  config: {}
  # Clients sends and final script
  sends: {}
  # Production essentials
  prod:
    script: {}
    storyboard: {}
    sound: {}
    reference: {}
 # CG Shot context
  "{scene}":
    "{shot}":
      nuke:
        - comp
        - prep
        - env
        - light
        - fx
      maya:
        - anim
        - light
        - modeler
        - texture
      houdini:
        - fx
        - env
        - crowds
      katana:
        - light
        - fx
      substance:
        - texture
      assets: {}
      renders: {}
